export const accounts = [
    {
        id: '1',
        name: 'Account Nickname',
        source: 'Bank of America',
        institution: 'Legends',
        mask: '1234',
        type: 'Checking',
    },
    {
        id: '2',
        name: 'Emergency Checking',
        source: 'Chase',
        institution: 'Legends',
        mask: '1234',
        type: 'Checking',
    },
    {
        id: '3',
        name: 'Money Pile Savings',
        source: 'Union Credit',
        institution: 'Legends',
        mask: '1234',
        type: 'Savings',
    },
];

export const transfers = [
    {
        __typename: 'Transfer',
        id: '88e1de98-444e-4187-91c9-e42a215cdf63',
        status: 'CANCELLED',
        type: 'DIVIDEND',
        sourceAccount: {
            __typename: 'Wallet',
            id: '258f5180-b942-48c3-bfc7-d3f53ad0c971',
            name: 'Auto Loan Account',
            type: 'SAVINGS',
            mask: 9801,
        },
        destinationAccount: {
            __typename: 'Wallet',
            id: 'e76df244-c0af-4de0-a312-6667e33e4004',
            name: 'Legends Wallet',
            type: 'WALLET',
            mask: null,
        },
        amount: '$64.49',
        created: '1630941069235',
        title: 'Dividend Payment',
        destinationName: 'Legends Wallet',
        sourceName: 'Auto Loan Account',
        color: 'eraserRed',
    },
    {
        __typename: 'Transfer',
        id: 'f6c2e649-2ca5-49c8-a9de-43b1c4efff14',
        status: 'FAILED',
        type: 'DIVIDEND',
        sourceAccount: {
            __typename: 'Wallet',
            id: 'fa67d6c7-5061-4d1c-aea8-7865b797b533',
            name: 'Checking Account',
            type: 'CHECKING',
            mask: 3834,
        },
        destinationAccount: {
            __typename: 'Wallet',
            id: 'e76df244-c0af-4de0-a312-6667e33e4004',
            name: 'Legends Wallet',
            type: 'WALLET',
            mask: null,
        },
        amount: '$32.77',
        created: '1644463061480',
        title: 'Dividend Payment',
        destinationName: 'Legends Wallet',
        sourceName: 'Checking Account',
        color: 'eraserRed',
    },
    {
        __typename: 'Transfer',
        id: 'c4549192-ac4c-45a8-a2c4-649b5a7cd5e2',
        status: 'FAILED',
        type: 'DIVIDEND',
        sourceAccount: {
            __typename: 'Wallet',
            id: 'e76df244-c0af-4de0-a312-6667e33e4004',
            name: 'Legends Wallet',
            type: 'WALLET',
            mask: null,
        },
        destinationAccount: {
            __typename: 'Wallet',
            id: 'e76df244-c0af-4de0-a312-6667e33e4004',
            name: 'Legends Wallet',
            type: 'WALLET',
            mask: null,
        },
        amount: '$29.78',
        created: '1622241934986',
        title: 'Dividend Payment',
        destinationName: 'Legends Wallet',
        sourceName: 'Legends Wallet',
        color: 'eraserRed',
    },
    {
        __typename: 'Transfer',
        id: '4718e0f4-a966-474d-a843-a254bc33bebb',
        status: 'FAILED',
        type: 'DIVIDEND',
        sourceAccount: {
            __typename: 'Wallet',
            id: 'da3b0d9a-c4d5-4e2e-adf4-434a0307c6f9',
            name: 'Personal Loan Account',
            type: 'SAVINGS',
            mask: 4389,
        },
        destinationAccount: {
            __typename: 'Wallet',
            id: 'e76df244-c0af-4de0-a312-6667e33e4004',
            name: 'Legends Wallet',
            type: 'WALLET',
            mask: null,
        },
        amount: '$59.15',
        created: '1634842265727',
        title: 'Dividend Payment',
        destinationName: 'Legends Wallet',
        sourceName: 'Personal Loan Account',
        color: 'eraserRed',
    },
];
