import Head from 'next/head';
import styles from '../styles/Home.module.css';

import {MetricGauge, energy} from 'component-lib';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MetricGauge
                min={0}
                message={'test'}
                max={10}
                currentValue={5}
                error={'ha'}
                unitOpts={energy}
            ></MetricGauge>
        </div>
    );
}
