name: Deploy to Dev Firebase Hosting on merge
'on':
  push:
    branches:
      - dev 
  pull_request:
    branches:
      - dev 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.DEV_FIREBASE_TOKEN }}'
          channelId: live
          projectId: legends-dev-362321
          target: dev-app
      - run: npm ci && npm run build:test
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.DEV_FIREBASE_TOKEN }}'
          channelId: live
          projectId: legends-dev-362321
          target: dev-components


