name: Deploy to Dev Firebase Hosting on merge
'on':
  push:
    branches:
      - dev 
  pull_request:
    branches:
      - dev 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Run Build 
        uses: borales/actions-yarn@v4
        with:
          cmd: build:dev 
          dir: 'packages/app_react'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.DEV_FIREBASE_TOKEN }}'
          channelId: live
          projectId: legends-dev-362321
          target: dev-app

